// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (user_id, parent_id, type, title, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at
`

type CreateNodeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Type      NodeType    `json:"type"`
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.UserID,
		arg.ParentID,
		arg.Type,
		arg.Title,
		arg.SortOrder,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChildren = `-- name: GetChildren :many
SELECT id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at FROM nodes
WHERE parent_id = $1 
  AND user_id = $2 
  AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type GetChildrenParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChildren(ctx context.Context, arg GetChildrenParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, getChildren, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at FROM nodes
WHERE id = $1 
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNodeByID(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteNode = `-- name: SoftDeleteNode :exec
UPDATE nodes
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type SoftDeleteNodeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteNode(ctx context.Context, arg SoftDeleteNodeParams) error {
	_, err := q.db.Exec(ctx, softDeleteNode, arg.ID, arg.UserID)
	return err
}
