// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package user

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, created_at, updated_at, avatar_url, timezone, locale, preferences, is_email_verified, last_login_at, deleted_at, verification_token, verification_token_expires_at, reset_password_token, reset_password_token_expires_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Timezone,
		&i.Locale,
		&i.Preferences,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.ResetPasswordToken,
		&i.ResetPasswordTokenExpiresAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, avatar_url, timezone, locale, preferences, is_email_verified, last_login_at, created_at, updated_at FROM users_public
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (UsersPublic, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i UsersPublic
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.Timezone,
		&i.Locale,
		&i.Preferences,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHashById = `-- name: GetUserPasswordHashById :one
SELECT password_hash FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserPasswordHashById(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHashById, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const setResetPasswordToken = `-- name: SetResetPasswordToken :exec
UPDATE users
SET 
    reset_password_token = $1, 
    reset_password_token_expires_at = NOW() + INTERVAL '15 minutes'
WHERE id = $2
`

type SetResetPasswordTokenParams struct {
	ResetPasswordToken pgtype.Text `json:"reset_password_token"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) SetResetPasswordToken(ctx context.Context, arg SetResetPasswordTokenParams) error {
	_, err := q.db.Exec(ctx, setResetPasswordToken, arg.ResetPasswordToken, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $1, reset_password_token = NULL, reset_password_token_expires_at = NULL
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users
SET 
    locale = COALESCE($1, locale),
    timezone = COALESCE($2, timezone),
    preferences = COALESCE(
        preferences || $3::jsonb, 
        preferences
    ),
    updated_at = NOW()
WHERE id = $4
RETURNING locale, timezone, preferences, updated_at
`

type UpdateUserPreferencesParams struct {
	Locale      pgtype.Text     `json:"locale"`
	Timezone    pgtype.Text     `json:"timezone"`
	Preferences json.RawMessage `json:"preferences"`
	ID          pgtype.UUID     `json:"id"`
}

type UpdateUserPreferencesRow struct {
	Locale      pgtype.Text        `json:"locale"`
	Timezone    pgtype.Text        `json:"timezone"`
	Preferences json.RawMessage    `json:"preferences"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.Locale,
		arg.Timezone,
		arg.Preferences,
		arg.ID,
	)
	var i UpdateUserPreferencesRow
	err := row.Scan(
		&i.Locale,
		&i.Timezone,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    username = COALESCE($1, username),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE id = $3
RETURNING username, avatar_url, updated_at
`

type UpdateUserProfileParams struct {
	Username  pgtype.Text `json:"username"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateUserProfileRow struct {
	Username  pgtype.Text        `json:"username"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Username, arg.AvatarUrl, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(&i.Username, &i.AvatarUrl, &i.UpdatedAt)
	return i, err
}
