// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, username)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, username, created_at, updated_at, avatar_url, timezone, locale, preferences, is_email_verified, last_login_at, deleted_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Username     pgtype.Text `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Timezone,
		&i.Locale,
		&i.Preferences,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, created_at, updated_at, avatar_url, timezone, locale, preferences, is_email_verified, last_login_at, deleted_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Timezone,
		&i.Locale,
		&i.Preferences,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, avatar_url, timezone, locale, preferences, is_email_verified, last_login_at, created_at, updated_at FROM users_public
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (UsersPublic, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i UsersPublic
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.Timezone,
		&i.Locale,
		&i.Preferences,
		&i.IsEmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users
SET 
    locale = COALESCE($1, locale),
    timezone = COALESCE($2, timezone),
    preferences = COALESCE(
        $3::jsonb || preferences, 
        preferences
    ),
    updated_at = NOW()
WHERE id = $4
RETURNING locale, timezone, preferences, updated_at
`

type UpdateUserPreferencesParams struct {
	Locale      pgtype.Text `json:"locale"`
	Timezone    pgtype.Text `json:"timezone"`
	Preferences []byte      `json:"preferences"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateUserPreferencesRow struct {
	Locale      pgtype.Text        `json:"locale"`
	Timezone    pgtype.Text        `json:"timezone"`
	Preferences []byte             `json:"preferences"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.Locale,
		arg.Timezone,
		arg.Preferences,
		arg.ID,
	)
	var i UpdateUserPreferencesRow
	err := row.Scan(
		&i.Locale,
		&i.Timezone,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    username = COALESCE($1, username),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE id = $3
RETURNING username, avatar_url, updated_at
`

type UpdateUserProfileParams struct {
	Username  pgtype.Text `json:"username"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateUserProfileRow struct {
	Username  pgtype.Text        `json:"username"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Username, arg.AvatarUrl, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(&i.Username, &i.AvatarUrl, &i.UpdatedAt)
	return i, err
}
