version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: backend_go
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - SERVER_PORT=${SERVER_PORT}
      - CONFIG_PATH=${CONFIG_PATH}
    depends_on:
      - db
  frontend:
    container_name: frontend_ts
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
volumes:
  postgres_data: