// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hierarchy.sql

package hierarchy

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAncestors = `-- name: GetAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT
        parent.id,
        parent.parent_id,
        1 AS depth
    FROM nodes AS node
    JOIN nodes AS parent
      ON parent.id = node.parent_id
     AND parent.user_id = node.user_id
     AND parent.deleted_at IS NULL
    WHERE node.id = $1
      AND node.user_id = $2
      AND node.deleted_at IS NULL

    UNION ALL

    SELECT
        parent.id,
        parent.parent_id,
        ancestors.depth + 1
    FROM ancestors
    JOIN nodes AS parent
      ON parent.id = ancestors.parent_id
     AND parent.user_id = $2
     AND parent.deleted_at IS NULL
)
SELECT n.id, n.user_id, n.parent_id, n.type, n.title, n.sort_order, n.created_at, n.updated_at, n.deleted_at
FROM ancestors AS a
JOIN nodes AS n
  ON n.id = a.id
 AND n.user_id = $2
 AND n.deleted_at IS NULL
ORDER BY a.depth DESC
`

type GetAncestorsParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAncestors(ctx context.Context, arg GetAncestorsParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, getAncestors, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildren = `-- name: GetChildren :many
SELECT id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at FROM nodes
WHERE parent_id = $1 
  AND user_id = $2 
  AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type GetChildrenParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChildren(ctx context.Context, arg GetChildrenParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, getChildren, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendants = `-- name: GetDescendants :many
WITH RECURSIVE descendants AS (
    SELECT
        child.id,
        child.parent_id,
        child.sort_order,
        ARRAY[child.sort_order] AS so_path,
        ARRAY[child.id] AS id_path
    FROM nodes AS child
    WHERE child.parent_id = $1
      AND child.user_id = $2
      AND child.deleted_at IS NULL

    UNION ALL

    SELECT
        child.id,
        child.parent_id,
        child.sort_order,
        d.so_path || child.sort_order,
        d.id_path || child.id
    FROM descendants AS d
    JOIN nodes AS child
      ON child.parent_id = d.id
     AND child.user_id = $2
     AND child.deleted_at IS NULL
)
SELECT n.id, n.user_id, n.parent_id, n.type, n.title, n.sort_order, n.created_at, n.updated_at, n.deleted_at
FROM descendants AS d
JOIN nodes AS n
  ON n.id = d.id
 AND n.user_id = $2
 AND n.deleted_at IS NULL
ORDER BY d.so_path, d.id_path
`

type GetDescendantsParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDescendants(ctx context.Context, arg GetDescendantsParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, getDescendants, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNode = `-- name: GetNode :one
SELECT id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at FROM nodes
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetNodeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetNode(ctx context.Context, arg GetNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getParent = `-- name: GetParent :one
SELECT parent.id, parent.user_id, parent.parent_id, parent.type, parent.title, parent.sort_order, parent.created_at, parent.updated_at, parent.deleted_at
FROM nodes AS node
JOIN nodes AS parent
  ON parent.id = node.parent_id
 AND parent.user_id = node.user_id
WHERE node.id = $1
  AND node.user_id = $2
  AND node.deleted_at IS NULL
  AND parent.deleted_at IS NULL
`

type GetParentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParent(ctx context.Context, arg GetParentParams) (Node, error) {
	row := q.db.QueryRow(ctx, getParent, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrevSiblingRank = `-- name: GetPrevSiblingRank :one
SELECT n.sort_order
FROM nodes AS n
WHERE n.parent_id IS NOT DISTINCT FROM $1::uuid
  AND n.user_id = $2
  AND n.deleted_at IS NULL
  AND n.id <> $3
  AND (
      $4::bigint IS NULL
      OR (n.sort_order, n.id) < ($4::bigint, $5::uuid)
  )
ORDER BY n.sort_order DESC, n.id DESC
LIMIT 1
`

type GetPrevSiblingRankParams struct {
	ParentID   pgtype.UUID `json:"parent_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ExcludeID  pgtype.UUID `json:"exclude_id"`
	BeforeRank pgtype.Int8 `json:"before_rank"`
	BeforeID   pgtype.UUID `json:"before_id"`
}

func (q *Queries) GetPrevSiblingRank(ctx context.Context, arg GetPrevSiblingRankParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPrevSiblingRank,
		arg.ParentID,
		arg.UserID,
		arg.ExcludeID,
		arg.BeforeRank,
		arg.BeforeID,
	)
	var sort_order int64
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getRoot = `-- name: GetRoot :one
WITH RECURSIVE ancestors AS (
    SELECT
        node.id,
        node.parent_id
    FROM nodes AS node
    WHERE node.id = $1
      AND node.user_id = $2
      AND node.deleted_at IS NULL

    UNION ALL

    SELECT
        parent.id,
        parent.parent_id
    FROM ancestors
    JOIN nodes AS parent
      ON parent.id = ancestors.parent_id
     AND parent.user_id = $2
     AND parent.deleted_at IS NULL
)
SELECT n.id, n.user_id, n.parent_id, n.type, n.title, n.sort_order, n.created_at, n.updated_at, n.deleted_at
FROM ancestors AS a
JOIN nodes AS n
  ON n.id = a.id
 AND n.user_id = $2
 AND n.deleted_at IS NULL
WHERE a.parent_id IS NULL
`

type GetRootParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRoot(ctx context.Context, arg GetRootParams) (Node, error) {
	row := q.db.QueryRow(ctx, getRoot, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubtree = `-- name: GetSubtree :many
WITH RECURSIVE subtree AS (
    SELECT
        node.id,
        node.parent_id,
        ARRAY[node.sort_order] AS so_path,
        ARRAY[node.id] AS id_path
    FROM nodes AS node
    WHERE node.id = $1
      AND node.user_id = $2
      AND node.deleted_at IS NULL

    UNION ALL

    SELECT
        child.id,
        child.parent_id,
        s.so_path || child.sort_order,
        s.id_path || child.id
    FROM subtree AS s
    JOIN nodes AS child
      ON child.parent_id = s.id
     AND child.user_id = $2
     AND child.deleted_at IS NULL
)
SELECT n.id, n.user_id, n.parent_id, n.type, n.title, n.sort_order, n.created_at, n.updated_at, n.deleted_at
FROM subtree AS s
JOIN nodes AS n
  ON n.id = s.id
 AND n.user_id = $2
 AND n.deleted_at IS NULL
ORDER BY s.so_path, s.id_path
`

type GetSubtreeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSubtree(ctx context.Context, arg GetSubtreeParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, getSubtree, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isInSubtree = `-- name: IsInSubtree :one
WITH RECURSIVE ancestors AS (
    SELECT
        node.id,
        node.parent_id,
        ARRAY[node.id] AS id_path
    FROM nodes AS node
    WHERE node.id = $2
      AND node.user_id = $3

    UNION ALL

    SELECT
        parent.id,
        parent.parent_id,
        ancestors.id_path || parent.id
    FROM ancestors
    JOIN nodes AS parent
      ON parent.id = ancestors.parent_id
     AND parent.user_id = $3
    WHERE NOT parent.id = ANY(ancestors.id_path)
)
SELECT COALESCE(bool_or(a.id = $1::uuid), false)::boolean AS is_in_subtree
FROM ancestors AS a
`

type IsInSubtreeParams struct {
	RootID pgtype.UUID `json:"root_id"`
	NodeID pgtype.UUID `json:"node_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsInSubtree(ctx context.Context, arg IsInSubtreeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInSubtree, arg.RootID, arg.NodeID, arg.UserID)
	var is_in_subtree bool
	err := row.Scan(&is_in_subtree)
	return is_in_subtree, err
}

const lockUserHierarchy = `-- name: LockUserHierarchy :exec
SELECT pg_advisory_xact_lock(hashtextextended('hierarchy:' || ($1::uuid)::text, 0))
`

func (q *Queries) LockUserHierarchy(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockUserHierarchy, userID)
	return err
}

const moveNode = `-- name: MoveNode :one
UPDATE nodes
SET
    parent_id = $1,
    sort_order = $2,
    updated_at = NOW()
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
RETURNING parent_id, sort_order, updated_at
`

type MoveNodeParams struct {
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int64       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type MoveNodeRow struct {
	ParentID  pgtype.UUID        `json:"parent_id"`
	SortOrder int64              `json:"sort_order"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MoveNode(ctx context.Context, arg MoveNodeParams) (MoveNodeRow, error) {
	row := q.db.QueryRow(ctx, moveNode,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
		arg.UserID,
	)
	var i MoveNodeRow
	err := row.Scan(&i.ParentID, &i.SortOrder, &i.UpdatedAt)
	return i, err
}

const rebalanceChildren = `-- name: RebalanceChildren :exec
UPDATE nodes AS n
SET sort_order = ranked.position * $1::bigint
FROM (
    SELECT
        c.id,
        ROW_NUMBER() OVER (ORDER BY c.sort_order, c.id) AS position
    FROM nodes AS c
    WHERE c.parent_id IS NOT DISTINCT FROM $2::uuid
      AND c.user_id = $3
      AND c.deleted_at IS NULL
      AND c.id <> $4
) AS ranked
WHERE n.id = ranked.id
`

type RebalanceChildrenParams struct {
	Gap       int64       `json:"gap"`
	ParentID  pgtype.UUID `json:"parent_id"`
	UserID    pgtype.UUID `json:"user_id"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) RebalanceChildren(ctx context.Context, arg RebalanceChildrenParams) error {
	_, err := q.db.Exec(ctx, rebalanceChildren,
		arg.Gap,
		arg.ParentID,
		arg.UserID,
		arg.ExcludeID,
	)
	return err
}
