// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package node

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (user_id, parent_id, type, title, sort_order)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE((
        SELECT MAX(sibling.sort_order)
        FROM nodes AS sibling
        WHERE sibling.user_id = $1
          AND sibling.parent_id IS NOT DISTINCT FROM $2::uuid
          AND sibling.deleted_at IS NULL
    ), 0) + $5::bigint
)
RETURNING id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at
`

type CreateNodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Type     NodeType    `json:"type"`
	Title    string      `json:"title"`
	Gap      int64       `json:"gap"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.UserID,
		arg.ParentID,
		arg.Type,
		arg.Title,
		arg.Gap,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, user_id, parent_id, type, title, sort_order, created_at, updated_at, deleted_at FROM nodes
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetNodeByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetNodeByID(ctx context.Context, arg GetNodeByIDParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, arg.ID, arg.UserID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteNodeCascade = `-- name: SoftDeleteNodeCascade :many
WITH RECURSIVE subtree AS (
    SELECT id 
    FROM nodes AS n
    WHERE n.id = $1 AND n.user_id = $2 AND n.deleted_at IS NULL
    
    UNION ALL
    
    SELECT c.id 
    FROM nodes AS c
    INNER JOIN subtree AS p ON c.parent_id = p.id
    WHERE c.user_id = $2 AND c.deleted_at IS NULL
)
UPDATE nodes
SET deleted_at = NOW() 
WHERE id IN (SELECT id FROM subtree)
RETURNING id
`

type SoftDeleteNodeCascadeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteNodeCascade(ctx context.Context, arg SoftDeleteNodeCascadeParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, softDeleteNodeCascade, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET
    type = COALESCE($1, type),
    title = COALESCE($2, title),
    updated_at = NOW()
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
RETURNING type, title, updated_at
`

type UpdateNodeParams struct {
	Type   NullNodeType `json:"type"`
	Title  pgtype.Text  `json:"title"`
	ID     pgtype.UUID  `json:"id"`
	UserID pgtype.UUID  `json:"user_id"`
}

type UpdateNodeRow struct {
	Type      NodeType           `json:"type"`
	Title     string             `json:"title"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (UpdateNodeRow, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.Type,
		arg.Title,
		arg.ID,
		arg.UserID,
	)
	var i UpdateNodeRow
	err := row.Scan(&i.Type, &i.Title, &i.UpdatedAt)
	return i, err
}
