// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NodeType string

const (
	NodeTypeFolder NodeType = "folder"
	NodeTypeNote   NodeType = "note"
	NodeTypeTask   NodeType = "task"
)

func (e *NodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeType(s)
	case string:
		*e = NodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeType: %T", src)
	}
	return nil
}

type NullNodeType struct {
	NodeType NodeType `json:"node_type"`
	Valid    bool     `json:"valid"` // Valid is true if NodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.NodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeType), nil
}

type Node struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Type      NodeType           `json:"type"`
	Title     string             `json:"title"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type NoteContent struct {
	NodeID    pgtype.UUID        `json:"node_id"`
	Content   json.RawMessage    `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Username        pgtype.Text        `json:"username"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Timezone        pgtype.Text        `json:"timezone"`
	Locale          pgtype.Text        `json:"locale"`
	Preferences     json.RawMessage    `json:"preferences"`
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UsersPublic struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Username        pgtype.Text        `json:"username"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Timezone        pgtype.Text        `json:"timezone"`
	Locale          pgtype.Text        `json:"locale"`
	Preferences     json.RawMessage    `json:"preferences"`
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
